version: '3.7'

volumes:
  mysqldata:
    driver: local

services:
  database:
    image: mysql
    container_name: mysql-xsolution-ead
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
    volumes:
      - mysqldata:/data/mysql
